VERSION = "2.0.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS = [
  "GDKSAFCZI3U4SIZAFGY2QWTOC7DFZJGDGSBC6VLSPFYLOII24W6KFUNS",
  "GAU3T7DAMRWP3X6HFXWQ64NKK7RMJWYHHJNXALWIX6EVJKDZLL2LUQLB"
]

[[CURRENCIES]]
code = "Home"
issuer = "GDKSAFCZI3U4SIZAFGY2QWTOC7DFZJGDGSBC6VLSPFYLOII24W6KFUNS"
display_decimals = 7
name = "Homeless Token"
desc = "Homeless Token â€” supporting homeless initiatives and community outreach programs."
conditions = "https://homeless.github.io/terms.html"
image = "https://homeless.github.io/homeless_logo.png"
is_unlimited = false
is_asset_anchored = false
status = "live"