VERSION = "2.0.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
HOME_DOMAIN = "homelesscommunitycare-hcc.github.io"

ACCOUNTS = [
  "GDKSAFCZI3U4SIZAFGY2QWTOC7DFZJGDGSBC6VLSPFYLOII24W6KFUNS",
  "GAU3T7DAMRWP3X6HFXWQ64NKK7RMJWYHHJNXALWIX6EVJKDZLL2LUQLB"
]

[[CURRENCIES]]
code = "HCC"
issuer = "GDKSAFCZI3U4SIZAFGY2QWTOC7DFZJGDGSBC6VLSPFYLOII24W6KFUNS"
display_decimals = 7
name = "Homeless Community Care "
desc = "Homeless Token HCC for short— supporting homeless initiatives and community outreach programs.Homeless Token was born from a simple, painful reality: too many people fall through the cracks, and the world moves on like nothing happened. 
	This token exists to make sure those people are never ignored again.
		Every Homeless Token carries the weight of someone’s cold night, someone’s empty stomach, someone’s quiet prayer that tomorrow might 
hurt less than today. It carries the story of the veteran sleeping under a bridge, the single parent holding a child close to stay warm, 
the teenager pretending they’re “just out walking” because admitting they have no place to go is too heavy to say out loud.
	This token fights for them.
		Homeless Token is a promise. A promise that someone out there still cares. That someone sees them. That someone believes they deserve more than 
survival. It turns compassion into fuel, and fuel into real help: blankets, shelter, food, protection, a moment of peace in a life that hasn’t
had any in too long.
		When you hold Homeless Token, you’re carrying the stories of people who never had anyone carry anything for them. You’re giving hope to 
someone who hasn’t felt hopeful in years. You’re part of the moment when a stranger goes from invisible, to seen.
	And maybe… just maybe… you help someone believe that life can start over. Homeless is NOT like these other guys asking for donations and only give 10% 
and keep 90% for themselves. Its the exact oppisite for us because we want you to know and see that 90% of your Hard erand money goes directly to help 
actually make a change in town's and cities just like yours. Homeless will establish a Headquarters for all base operations as well as purchas of Mobile
food trucks that will not just serve hot meals free of charge to those in need on the streets, but the food trucks will also be serving the general public
at events all over the country. Which in turn also goes back to Homeless for necessary restocks of supplies and food for emergency aid in natural disaster
areas. These are our short term goals for the nearest future. With Gods blessings and your generious token and donation purchases. God will grant us these
much needed blessings. From the founder and CEO of Homeless, Jason Cook I thank you and God Bless.  Oh and Remember:
		Homeless Token isn’t about crypto. It’s about humanity. And humanity is worth everything."
		
conditions = "https://homelesscommunitycare-hcc.github.io"

image = "https://homelesscommunitycare-hcc.github.io/homeless2_logo.png"

is_unlimited = false
is_asset_anchored = false
status = "live"
