VERSION = "2.0.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[[CURRENCIES]]
issuer = GDKSAFCZI3U4SIZAFGY2QWTOC7DFZJGDGSBC6VLSPFYLOII24W6KFUNS
display_decimals = 7
name = "Homeless Token"
desc = "A token dedicated to supporting homeless initiatives and community outreach programs"

conditions = "https://homeless.github.io/terms.html"
image = "https://homeless.github.io/homeless_logo.png"
is_unlimited = false
is_asset_anchored = false
status = "live"
